source "$HOME/settings/antigen/antigen.zsh"

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle cabal

# Load the theme.
antigen theme https://gist.github.com/zoomix/3827269 agnoster-light.zsh-theme

# Tell antigen that you're done.
antigen apply

# Auto-correction mode on.
ENABLE_CORRECTION="true"

# Emacs keybindings
bindkey -e

# Personal aliases.
alias -g NS="nix-env -qaP '*'"
alias -g G="| grep -i"
alias -g L="| less"
alias -s pdf=zathura

alias e="emacsclient -t"

function hub {
    git clone "https://github.com/$1"
}
