source "$HOME/settings/antigen/antigen.zsh"

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle cabal

# Load the theme.
antigen theme https://gist.github.com/zoomix/3827269 agnoster-light.zsh-theme

# Tell antigen that you're done.
antigen apply

# Auto-correction mode on.
ENABLE_CORRECTION="true"

# Emacs keybindings
bindkey -e

# Personal aliases.
alias -g NS="nix-env -qaP '*'"
alias -g G="| grep -i"
alias -g L="| less"
alias -s pdf=zathura

alias e="emacsclient -t"

alias nixpaste="curl -F 'text=<-' http://nixpaste.noip.me"

# Aliases for ghc-mod integration with ghcWithPackages
NIX_GHC_VERSION=$(ghc --numeric-version)
export NIX_GHC="$HOME/.nix-profile/bin/ghc"
export NIX_GHCPKG="$HOME/.nix-profile/bin/ghc-pkg"
export NIX_GHC_DOCDIR="$HOME/.nix-profile/share/doc/ghc/html"
export NIX_GHC_LIBDIR="$HOME/.nix-profile/lib/ghc-${NIX_GHC_VERSION}"

function hub {
    git clone "https://github.com/$1"
}

# Questo e' un export per cask

export PATH="/home/carlo/.cask/bin:$PATH"