;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-delete
        evil-exit-emacs-state
        evil-forward-char
        evil-next-line
        evil-previous-line
        haskell-mode-contextual-space
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        evil-backward-char
        evil-force-normal-state
        evil-insert
        evil-search-next
        smex
        yas-expand
        ))
